### ISSUE TITLE
Mining is broken

### ISSUE THREAD

**Issue by tommyp6** [quackduck/duckcoin#12]
Whenever you mine, you get that the block hash is incorrect. I have done `git pull` and restarted all my miners to see if I had outdated code, however that didn't work. 

```
Mining to this address: 2zRNlDy4PFHZe7TQAEwX7BbnN7DGC0QQKdVlCP5k+DM=
Approx hashrate: 72288.83. Have checked 131072 hashes.
Approx hashrate: 71045.51. Have checked 262144 hashes.
Approx hashrate: 66310.32. Have checked 393216 hashes.
Approx hashrate: 66062.97. Have checked 524288 hashes.
Approx hashrate: 66497.15. Have checked 655360 hashes.

Block made! It took 11.55s
{
   "Index": 189494,
   "Timestamp": 1631196322419704,
   "Data": "Mined by the official Duckcoin CLI User: ",
   "Hash": "00000ffbe34bff75d98b142401df5b2011a4a5a2de06ed013052a47d09df4391",
   "PrevHash": "00000eaf24732c71e5ce05da3e6755813570205e8e1b2236f70512e6666e3c15",
   "Solution": "758738",
   "Solver": "2zRNlDy4PFHZe7TQAEwX7BbnN7DGC0QQKdVlCP5k+DM=",
   "Tx": {
      "Data": "",
      "Sender": "",
      "Receiver": "",
      "Amount": 0,
      "PubKey": "",
      "Signature": ""
   }
}
Sent block to server
Server returned "Invalid block. Block Hash is incorrect. This usually happens if your Difficulty is set incorrectly. Restart your miner."
```

I need to mine to become the richest quack holder :sob:
I have looked at the code to see if I could spot the issue, but haven't been able to so far. Will update you if I find anything.

**Comment by l3gacyb3ta** [comment]
Hm. I'll look at this!

**Comment by devenjadhav** [comment]
helloooo

**Comment by l3gacyb3ta** [comment]
Ok, @TommyPujol06 are you running the latest the latest version of the client? You might have to rebuild the binary.

**Comment by quackduck** [comment]
@TommyPujol06 are you sure you built the code? Run “go install” in the snode-src directory. ~it works on my machine~

**Comment by l3gacyb3ta** [comment]
@quackduck pls review my pr

**Comment by quackduck** [comment]
Send a sha256 hash of the binary (specify OS) so I can check whether it’s the latest.

**Comment by tommyp6** [comment]
> Ok, @TommyPujol06 are you running the latest the latest version of the client? You might have to rebuild the binary.

Yes, I am running the latest version. Re-building worked. I can mine again now. Must have forgotten to rebuild after fetching the new code.

**Comment by quackduck** [comment]
Glad it worked out

**Comment by l3gacyb3ta** [comment]
perfect!
