### ISSUE TITLE
Vuln: Address guajBQHIUUQ52MeJo9upYLCUNfNqAp3FoV+5sAANNA8= has more duckcoin than there have been blocks.

### ISSUE THREAD

**Issue by quackduck** [quackduck/duckcoin#20]
https://twitter.com/0xIshan/status/1469501360760451075

A lot of blocks mined by them seem to be having their own address as both the sender and receiver: see block 472613 and screenshot:

<img width="2242" alt="image" src="https://user-images.githubusercontent.com/38882631/145661495-4f74fb18-e719-448e-82bc-a90bcb04fdca.png">

**Comment by l3gacyb3ta** [comment]
Is it a rounding error?

**Comment by quackduck** [comment]
There is no rounding anywhere in the source, nor is there any floating point error

**Comment by quackduck** [comment]
(since internally amounts are expressed in terms of the minimum unit: a microquack)
